name:                fp-lab2
version:             0.1.0.0
github:              "WWamich/fp-lab2"
license:             BSD-3-Clause
author:              "WWamich" 
maintainer:          "admiral3233@mail.ru"

ghc-options:
- -Wall
- -Werror

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  task:
    main:                Main.hs
    source-dirs:         app
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - fp-lab2


tests:
  fp-lab2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - fp-lab2
    - tasty
    - tasty-hunit
