resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/1.yaml

packages:
- .
extra-deps:
- ormolu-0.8.0.2@sha256:4f85ee1053234827cec315f4307ce058b048ede13e29a6f2f21eaea7606261c7,5125
