name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true

    - name: Cache stack directories
      uses: actions/cache@v4
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install dependencies (incl. hlint, ormolu)
      run: stack build --dependencies-only --test

    - name: Check formatting with ormolu
      run: stack exec ormolu -- --mode check --color always .

    - name: Run hlint
      run: stack exec hlint -- --no-exit-code .

    - name: Build project
      run: stack build

    - name: Run tests
      run: stack test