name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true

    - name: Cache stack directories
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
        path: |
          ~/.stack
          .stack-work


    - name: Install hlint and ormolu
      run: stack install hlint ormolu

    - name: Check formatting with ormolu
      run: find . -name "*.hs" -exec stack exec ormolu -- --mode check --color always {} +

    - name: Run hlint
      run: stack exec hlint -- --no-exit-code .

    
    - name: Build and test project
      run: stack test