name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-version: 'latest'

    - name: Cache stack directories
      uses: actions/cache@v4
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies and some tools
      run: stack build --test --bench --dependencies-only

    - name: Check formatting with ormolu
      run: find src app test -type f -name "*.hs" -exec stack exec ormolu -- --mode check --color always {} +
    - name: Run hlint
      run: stack exec hlint -- --no-exit-code .

    - name: Build and test project
      run: stack test